# Docker-Compose-Konfiguration für Fahrradwerkstatt ERP basierend auf ERPNext
# Erstellt: 04.05.2025
# Diese Konfiguration stellt eine komplette ERPNext-Umgebung bereit

version: '3'

services:
  traefik:
    image: traefik:2.5
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=erpnext
      - MYSQL_USER=erpnext
      - MYSQL_PASSWORD=erpnext
      - MYSQL_DATABASE=erpnext
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    image: redis:6
    restart: always
    volumes:
      - redis-data:/data

  erpnext-app:
    image: frappe/erpnext:v14
    restart: always
    environment:
      - FRAPPE_PY=0.0.0.0:8000
      - FRAPPE_SOCKETIO=0.0.0.0:9000
      - FRAPPE_WS=0.0.0.0:9001
      - SKIP_ASSETS=1
      - DB_HOST=mariadb
      - DB_PORT=3306
      - REDIS_CACHE=redis:6379/0
      - REDIS_QUEUE=redis:6379/1
      - REDIS_SOCKETIO=redis:6379/2
      - DB_ROOT_USER=root
      - DB_ROOT_PASSWORD=erpnext
      - DB_NAME=erpnext
      - DB_PASSWORD=erpnext
      - DB_USER=erpnext
    volumes:
      - erpnext-sites:/home/frappe/frappe-bench/sites
      - custom-apps:/home/frappe/frappe-bench/apps/fahrradwerkstatt
    labels:
      - traefik.enable=true
      - traefik.http.routers.erpnext.rule=Host(`erpnext.localhost`)
      - traefik.http.services.erpnext.loadbalancer.server.port=8000

  erpnext-worker:
    image: frappe/erpnext:v14
    restart: always
    command: worker
    environment:
      - FRAPPE_PY=0.0.0.0:8000
      - FRAPPE_SOCKETIO=0.0.0.0:9000
      - FRAPPE_WS=0.0.0.0:9001
      - DB_HOST=mariadb
      - DB_PORT=3306
      - REDIS_CACHE=redis:6379/0
      - REDIS_QUEUE=redis:6379/1
      - REDIS_SOCKETIO=redis:6379/2
      - DB_ROOT_USER=root
      - DB_ROOT_PASSWORD=erpnext
      - DB_NAME=erpnext
      - DB_PASSWORD=erpnext
      - DB_USER=erpnext
    volumes:
      - erpnext-sites:/home/frappe/frappe-bench/sites
      - custom-apps:/home/frappe/frappe-bench/apps/fahrradwerkstatt

  erpnext-socketio:
    image: frappe/erpnext:v14
    restart: always
    command: node-socketio
    environment:
      - FRAPPE_PY=0.0.0.0:8000
      - FRAPPE_SOCKETIO=0.0.0.0:9000
      - FRAPPE_WS=0.0.0.0:9001
      - SKIP_ASSETS=1
      - DB_HOST=mariadb
      - DB_PORT=3306
      - REDIS_CACHE=redis:6379/0
      - REDIS_QUEUE=redis:6379/1
      - REDIS_SOCKETIO=redis:6379/2
    volumes:
      - erpnext-sites:/home/frappe/frappe-bench/sites

  erpnext-web:
    image: frappe/erpnext:v14
    restart: always
    command: yarn start
    environment:
      - FRAPPE_PY=erpnext-app:8000
      - FRAPPE_SOCKETIO=erpnext-socketio:9000
      - FRAPPE_WS=erpnext-app:9001
    labels:
      - traefik.enable=true
      - traefik.http.routers.erpnext-web.rule=Host(`erpnext.localhost`)
      - traefik.http.services.erpnext-web.loadbalancer.server.port=3000

volumes:
  mariadb-data:
  redis-data:
  erpnext-sites:
  custom-apps: